export const classicQueries = [
  "Aap Ke Aa Jaane Se Khudgarz",
  "Aate Jaate Hanste Gaate Maine Pyar Kiya",
  "Aye Mere Humsafar Qayamat Se Qayamat Tak",
  "Papa Kehte Hain Qayamat Se Qayamat Tak",
  "Gazab Ka Hai Din Qayamat Se Qayamat Tak",
  "Ek Ladki Ko Dekha 1942 A Love Story",
  "Humein Tumse Pyaar Kitna Kudrat",
  "Hamein Aur Jeene Ki Agar Tum Na Hote",
  "Tujhse Naraz Nahin Zindagi Masoom",
  "Lakdi Ki Kaathi Masoom",
  "Zindagi Ki Yahi Reet Hai Mr India",
  "Kaate Nahi Kat Te Mr India",
  "Hawa Hawaii Mr India",
  "Keh Do Ki Tum Tezaab",
  "Ek Do Teen Tezaab",
  "So Gaya Yeh Jahan Tezaab",
  "O O Jaane Jaana Pyaar Kiya To Darna Kya",
  "Mere Rang Mein Rangne Wali Maine Pyar Kiya",
  "Dil Deewana Maine Pyar Kiya",
  "Mere Haath Mein Dil",
  "Tere Mere Beech Mein Ek Duuje Ke Liye",
  "Solah Baras Ki Bali Umar Ek Duuje Ke Liye",
  "Aye Zindagi Gale Lagaa Le Sadma",
  "Pyar Kiya Hai Tumhi Se The Burning Train",
  "Zindagi Pyar Ka Geet Hai Souten",
  "Neele Neele Ambar Par Kalaakaar",
  "Hoga Tumse Pyara Kaun Zamaane Ko Dikhana Hai",
  "De De Pyaar De Sharaabi",
  "Inteha Ho Gayi Intezaar Ki Sharaabi",
  "Yeh Kahan Aa Gaye Hum Silsila",
  "Dekho Maine Dekha Hai Ek Sapna Love Story",
  "Yaad Aa Rahi Hai Love Story",
  "I Love You Mr India",
  "Kya Yahi Pyaar Hai Rocky",
  "Aye Dil-e-Nadaan Razia Sultan",
  "Pehla Nasha Jo Jeeta Wohi Sikandar",
  "Aisa Kyun Hota Hai Dil",
  "Mujhe Neend Na Aaye Dil",
  "Ae Kaash Ke Hum Kabhi Haan Kabhi Naa",
  "Do Dil Mil Rahe Hain Pardes",
  "Tum Mile Dil Khile Criminal",
  "Dheere Dheere Se Meri Zindagi Mein Aana Aashiqui",
  "Nazar Ke Saamne Aashiqui",
  "Tu Meri Zindagi Hai Aashiqui",
  "Ab Tere Bin Aashiqui",
  "Bahut Pyaar Karte Hain Saajan",
  "Mera Dil Bhi Kitna Pagal Hai Saajan",
  "Jeeye To Jeeye Kaise Saajan",
  "Pehli Pehli Pyar Ki Ilzaam",
  "Kuch Na Kaho 1942 A Love Story",
  "Rooth Na Jaana 1942 A Love Story",
  "Tujhe Dekha To Dilwale Dulhania Le Jayenge",
  "Ho Gaya Hai Tujhko To Pyaar Sajna Dilwale Dulhania Le Jayenge",
  "Mere Khwabon Mein Dilwale Dulhania Le Jayenge",
  "Bholi Si Surat Dil To Pagal Hai",
  "Are Re Are Dil To Pagal Hai",
  "Pyar Kar Dil To Pagal Hai",
  "Chaiyya Chaiyya Dil Se",
  "Satrangi Re Dil Se",
  "Jiya Jale Dil Se",
  "Aankhon Se Tune Kya Keh Diya Ghulam",
  "Pardesi Pardesi Raja Hindustani",
  "Aaye Ho Meri Zindagi Mein Raja Hindustani",
  "Mera Mann Mann",
  "Aankhon Ki Gustakhiyan Hum Dil De Chuke Sanam",
  "Tadap Tadap Ke Hum Dil De Chuke Sanam",
  "Nimbooda Hum Dil De Chuke Sanam"
];

export const hindiQueries = [
  "Kaho Naa Pyaar Hai Kaho Naa Pyaar Hai",
  "Ek Pal Ka Jeena Kaho Naa Pyaar Hai",
  "Humko Humise Chura Lo Mohabbatein",
  "Aankhein Khuli Mohabbatein",
  "Dil Ne Yeh Kaha Hai Dil Se Dhadkan",
  "Mitwa Kabhi Khushi Kabhie Gham",
  "Bole Chudiyan Kabhi Khushi Kabhie Gham",
  "Suraj Hua Maddham Kabhi Khushi Kabhie Gham",
  "Tum Bin Tum Bin",
  "Tere Bin Bas Ek Pal",
  "Aankhon Mein Teri Om Shanti Om",
  "Main Agar Kahoon Om Shanti Om",
  "Ajab Si Om Shanti Om",
  "Kal Ho Naa Ho Kal Ho Naa Ho",
  "It's the Time to Disco Kal Ho Naa Ho",
  "Pretty Woman Kal Ho Naa Ho",
  "Tum Se Hi Jab We Met",
  "Aaoge Jab Tum Jab We Met",
  "Mauja Hi Mauja Jab We Met",
  "Tere Bina Guru",
  "Kajra Re Bunty Aur Babli",
  "Dus Bahane Dus",
  "Dola Re Dola Devdas",
  "Silsila Ye Chaahat Ka Devdas",
  "Aankh Hai Bhari Bhari Tum Se Achcha Kaun Hai",
  "Saathiya Saathiya",
  "Chupke Se Saathiya",
  "Aao Milo Chalo Jab We Met",
  "Zara Sa Jannat",
  "Jiya Dhadak Dhadak Jaye Kalyug",
  "Kaho Na Kaho Murder",
  "Bheegey Hont Tere Murder",
  "Tu Hi Meri Shab Hai Gangster",
  "Ya Ali Gangster",
  "Teri Ore Singh Is Kinng",
  "Tum Hi Ho Aashiqui 2",
  "Chahun Main Ya Naa Aashiqui 2",
  "Sun Raha Hai Aashiqui 2",
  "Tujhe Kitna Chahne Lage Kabir Singh",
  "Agar Tum Saath Ho Tamasha",
  "Kun Faya Kun Rockstar",
  "Phir Se Ud Chala Rockstar",
  "Tum Ho Rockstar",
  "Iktara Wake Up Sid",
  "Kabira Yeh Jawaani Hai Deewani",
  "Badtameez Dil Yeh Jawaani Hai Deewani",
  "Ilahi Yeh Jawaani Hai Deewani",
  "Subhanallah Yeh Jawaani Hai Deewani",
  "Tera Ban Jaunga Kabir Singh",
  "Kaise Hua Kabir Singh",
  "Gerua Dilwale",
  "Janam Janam Dilwale",
  "Samjhawan Humpty Sharma Ki Dulhania",
  "Muskurane CityLights",
  "Pee Loon Once Upon a Time in Mumbaai",
  "Tum Jo Aaye Once Upon a Time in Mumbaai",
  "Tera Hone Laga Hoon Ajab Prem Ki Ghazab Kahani",
  "Raabta Agent Vinod",
  "Jeene Laga Hoon Ramaiya Vastavaiya",
  "Pehli Dafa Atif Aslam",
  "Hawayein Jab Harry Met Sejal",
  "Apna Bana Le Bhediya",
  "Kesariya Brahmāstra",
  "Rasiya Brahmāstra",
  "Chaleya Jawan",
  "Heeriye Jasleen Royal",
  "Sajni Laapataa Ladies",
  "Aaj Ki Raat Stree 2",
  "Tauba Tauba Bad Newz",
  "Aayi Nai Stree 2",
  "Tainu Khabar Nahi Munjya",
  "Ami Je Tomar 3.0 Bhool Bhulaiyaa 3"
];

export const bengaliQueries = [
  "Pherari Mon Antaheen Shreya Ghoshal",
  "Ekla Ghor Fossils",
  "Aro Ekbar Fossils",
  "Majhi Re The Bong Connection Shaan",
  "Rimjhim E Dharate Premer Kahini Shreya Ghoshal",
  "Chokhe Chokhe Premer Kahini Shaan Shreya Ghoshal",
  "Chupi Chupi Raat Chalo Let's Go",
  "Amake Amar Moto Thakte Dao Anupam Roy",
  "Boba Tunnel Anupam Roy",
  "Benche Thakar Gaan Autograph Rupam Islam",
  "Shei Tumi Keno Eto Ochena Hole",
  "Keno Megh Ashe Hridoy Akashe",
  "Tomar Jonno Arnob",
  "Hariye Giyechi Arnob",
  "Chiltey Roud Fossils",
  "Hashnuhana Fossils",
  "Ami Tomar Premey Chirodini Tumi Je Amar",
  "Mon Mane Na Mon Mane Na",
  "Bhalobasha Aajkal Bhalobasha Aajkal",
  "Kichu Kotha Chilo Chokhe Antaheen",
  "Bojhena Shey Bojhena Arijit Singh",
  "Mon Majhi Re Boss Arijit Singh",
  "Tomake Chai Gangster Arijit Singh",
  "E Tumi Kemon Tumi Chotushkone Anupam Roy",
  "Amar Mawte Belaseshe Anupam Roy",
  "Keno Emon Hoy Baishe Srabon Anupam Roy",
  "Chol Rastay Chalo Paltai",
  "Tumi Jake Bhalobasho Praktan Iman Chakraborty",
  "Kolkata Nirbaak Anupam Roy",
  "Ei Bhalo Ei Kharap Chirodini Tumi Je Amar 2",
  "Moner Manush Anirban Chatterjee",
  "Shono Go Dakhin Hawa Rang Milanti",
  "Tumi Ashbe Bole Chotushkone",
  "Jani Dekha Hobe Bojhena Shey Bojhena",
  "Preme Pora Baron Sweater Lagnajita Chakraborty",
  "Adure Din Sweater Ranajoy Bhattacharjee",
  "Tomake Female Parineeta Shreya Ghoshal",
  "Amaro Porano Jaha Chay",
  "Tumi Robe Nirobe",
  "Amar Shonar Bangla",
  "Majhe Majhe Tobo Dekha Pai",
  "Ami Chini Go Chini",
  "Tomar Holo Shuru",
  "Sokhi Bhabona Kahare Bole",
  "Pagla Hawar Badol Dine",
  "Ami Tomaro Shonge Bedhechi Amar Pran",
  "Jokhon Porbe Na Mor Payer Chinho"
];

export const classicalQueries = [
  "Raga Bhairav Pandit Bhimsen Joshi",
  "Raga Ahir Bhairav Ustad Rashid Khan",
  "Raga Ramkali Ustad Amir Khan",
  "Raga Lalit Pandit Jasraj",
  "Raga Todi Ustad Amir Khan",
  "Raga Miyan Ki Todi Pandit Bhimsen Joshi",
  "Raga Gujari Todi Ustad Rashid Khan",
  "Raga Jaunpuri Pandit Mallikarjun Mansur",
  "Raga Deshkar Pandit V. G. Jog",
  "Raga Jogiya Ustad Rashid Khan",
  "Raga Brindavani Sarang Pandit Bhimsen Joshi",
  "Raga Shuddha Sarang Pandit Jasraj",
  "Raga Multani Ustad Amir Khan",
  "Raga Bhimpalasi Pandit Bhimsen Joshi",
  "Raga Patdeep Pandit Kumar Gandharva",
  "Raga Shree Ustad Rashid Khan",
  "Raga Madhuvanti Pandit Jasraj",
  "Raga Marwa Ustad Amir Khan",
  "Raga Puriya Pandit Nikhil Banerjee",
  "Raga Puriya Dhanashree Pandit Bhimsen Joshi",
  "Raga Yaman Ustad Rashid Khan",
  "Raga Yaman Pandit Bhimsen Joshi",
  "Raga Maru Bihag Ustad Amir Khan",
  "Raga Bihag Pandit Jasraj",
  "Raga Kedar Pandit Bhimsen Joshi",
  "Raga Hameer Ustad Rashid Khan",
  "Raga Shyam Kalyan Pandit Jasraj",
  "Raga Shankara Ustad Amir Khan",
  "Raga Jait Pandit Jasraj",
  "Raga Jaijaiwanti Ustad Rashid Khan",
  "Raga Darbari Kanada Ustad Amir Khan",
  "Raga Darbari Kanada Pandit Bhimsen Joshi",
  "Raga Malkauns Ustad Amir Khan",
  "Raga Malkauns Pandit Ravi Shankar",
  "Raga Bageshri Pandit Bhimsen Joshi",
  "Raga Bageshri Ustad Rashid Khan",
  "Raga Chandrakauns Pandit Jasraj",
  "Raga Adana Ustad Amir Khan",
  "Raga Rageshri Ustad Rashid Khan",
  "Raga Kaunsi Kanada Pandit Bhimsen Joshi",
  "Raga Yaman Pandit Ravi Shankar",
  "Raga Bhairavi Ustad Bismillah Khan",
  "Raga Darbari Ustad Bismillah Khan",
  "Raga Puriya Kalyan Ustad Vilayat Khan",
  "Raga Shree Pandit Ravi Shankar",
  "Raga Bhimpalasi Pandit Nikhil Banerjee",
  "Raga Bageshri Pandit Nikhil Banerjee",
  "Raga Jog Ustad Vilayat Khan",
  "Raga Kafi Ustad Shahid Parvez",
  "Raga Kirwani Pandit Shivkumar Sharma",
  "Babul Mora Naihar Chhooto Jaye Ustad Bismillah Khan",
  "Ka Karun Sajni Aaye Na Balam Ustad Rashid Khan",
  "Yaad Piya Ki Aaye Begum Akhtar",
  "Humri Atariya Pe Aao Sanwariya Begum Akhtar",
  "Ae Mohabbat Tere Anjaam Pe Rona Aaya Begum Akhtar",
  "Piya Ke Milan Ki Aas Begum Akhtar",
  "Mohe Panghat Pe Nandlal Lata Mangeshkar",
  "Kahe Ched Ched Mohe Kavita Krishnamurti",
  "Albela Sajan Shubha Mudgal",
  "Kesariya Balam",
  "Man Tarpat Hari Darshan Ko Aaj Baiju Bawra Mohammed Rafi",
  "Mohe Bhool Gaye Sanwariya Baiju Bawra Lata Mangeshkar",
  "Madhuban Mein Radhika Nache Re Kohinoor Mohammed Rafi",
  "Albela Sajan Bajirao Mastani Shashi Suman",
  "Aaj Jaane Ki Zid Na Karo Farida Khanum",
  "Kehna Hi Kya Bombay Chitra",
  "O Rangrez Bhaag Milkha Bhaag Shreya Ghoshal",
  "Pinga Bajirao Mastani Shreya Ghoshal",
  "Mohe Rang Do Laal Bajirao Mastani Shreya Ghoshal",
  "Laal Ishq Goliyon Ki Raasleela Ram-Leela Arijit Singh"
];

export const rapQueries = [
  "Mere Gully Mein Divine Naezy",
  "Aafat Wapas Bohemia",
  "Kali Denali Bohemia",
  "Vich Pardesan De Bohemia",
  "Kali Gaddi Bohemia",
  "Pesa Nasha Pyar Bohemia",
  "Manju Bohemia",
  "Tere Bin Bohemia",
  "Kali Kali Ankhein Bohemia",
  "Ek Tera Pyar Bohemia",
  "Yeh Mera Bombay DIVINE",
  "Jungli Sher DIVINE",
  "3:59 AM DIVINE",
  "Kaam 25 DIVINE",
  "Gandhi Money DIVINE",
  "Mirchi DIVINE",
  "Baazigar DIVINE",
  "Chal Bombay DIVINE",
  "One Side DIVINE",
  "Satya DIVINE",
  "Aur Bantai Emiway Bantai",
  "Machayenge Emiway Bantai",
  "Samajh Mein Aaya Kya? Emiway Bantai",
  "Firse Machayenge Emiway Bantai",
  "What Can I Do Emiway Bantai",
  "Khatam Hue Waande Emiway Bantai",
  "Company Emiway Bantai",
  "Asli Hip Hop Ranveer Singh",
  "Apna Time Aayega Ranveer Singh",
  "Sher Aaya Sher DIVINE",
  "Namastute Seedhe Maut",
  "Nanchaku Seedhe Maut",
  "101 Seedhe Maut",
  "Do Guna Seedhe Maut",
  "Batti Seedhe Maut",
  "Maina Seedhe Maut",
  "Kranti Seedhe Maut",
  "Kohra Seedhe Maut",
  "MMM Seedhe Maut",
  "Hola Amigo Seedhe Maut",
  "Vyanjan KR$NA",
  "Makasam KR$NA",
  "Villin KR$NA",
  "Kaisa Mera Desh KR$NA",
  "Blowing Up KR$NA",
  "No Cap KR$NA",
  "Still Here KR$NA",
  "Fall Off KR$NA",
  "Na Hai KR$NA",
  "Saza-E-Maut KR$NA Raftaar",
  "Swag Mera Desi Raftaar",
  "Dhaakad Raftaar",
  "Mantoiyat Raftaar",
  "Awein Hai Raftaar",
  "All Black Raftaar",
  "Ghana Kasoota Raftaar",
  "Damn Raftaar",
  "Naachne Ka Shaunq Raftaar",
  "Bajre Da Sitta Noor Chahal",
  "Main Wahi Hoon Raftaar",
  "Basti Ka Hasti DIVINE",
  "Gandi Aulaad Seedhe Maut",
  "Kaha Tak Seedhe Maut",
  "TT/Shutdown Seedhe Maut",
  "Gumaan Young Stunners",
  "Afsanay Young Stunners",
  "Agency Talha Anjum",
  "Downers at Dusk Talha Anjum",
  "Gulshan-E-Hadeed Talha Anjum",
  "Haath Baandh Talha Anjum"
];

export const englishQueries = [
  "Coldplay Yellow",
  "Eminem Lose Yourself",
  "Linkin Park In the End",
  "Linkin Park Numb",
  "The Killers Mr. Brightside",
  "Green Day Boulevard of Broken Dreams",
  "Avril Lavigne Complicated",
  "Avril Lavigne Sk8er Boi",
  "Britney Spears Toxic",
  "Beyoncé Crazy in Love",
  "Rihanna Umbrella",
  "Rihanna Disturbia",
  "Akon Lonely",
  "Akon Smack That",
  "50 Cent In Da Club",
  "Nelly Dilemma",
  "Usher Yeah!",
  "Justin Timberlake Cry Me a River",
  "Maroon 5 This Love",
  "Maroon 5 She Will Be Loved",
  "The Black Eyed Peas Where Is the Love?",
  "The Pussycat Dolls Don't Cha",
  "Lady Gaga Poker Face",
  "Lady Gaga Bad Romance",
  "Amy Winehouse Back to Black",
  "Adele Rolling in the Deep",
  "Adele Someone Like You",
  "Ed Sheeran Thinking Out Loud",
  "Ed Sheeran Perfect",
  "Bruno Mars Just the Way You Are",
  "Bruno Mars Locked Out of Heaven",
  "Bruno Mars When I Was Your Man",
  "Taylor Swift Love Story",
  "Taylor Swift Blank Space",
  "Taylor Swift Style",
  "The Weeknd Can't Feel My Face",
  "The Weeknd Starboy",
  "The Weeknd The Hills",
  "Sia Chandelier",
  "Imagine Dragons Radioactive",
  "Imagine Dragons Demons",
  "OneRepublic Counting Stars",
  "Passenger Let Her Go",
  "John Legend All of Me",
  "Sam Smith Stay With Me",
  "Hozier Take Me to Church",
  "Gotye Somebody That I Used to Know",
  "Lana Del Rey Summertime Sadness",
  "Lorde Royals",
  "Coldplay A Sky Full of Stars",
  "The Weeknd Blinding Lights",
  "Dua Lipa Levitating",
  "Olivia Rodrigo drivers license",
  "Olivia Rodrigo vampire",
  "Billie Eilish Happier Than Ever",
  "Miley Cyrus Flowers",
  "SZA Kill Bill",
  "Sabrina Carpenter Espresso",
  "Sabrina Carpenter Please Please Please",
  "Chappell Roan Good Luck, Babe!",
  "Lady Gaga Bruno Mars Die With a Smile",
  "Benson Boone Beautiful Things",
  "Tate McRae greedy",
  "ROSÉ Bruno Mars APT.",
  "Billie Eilish BIRDS OF A FEATHER",
  "Chappell Roan Pink Pony Club",
  "The Weeknd Save Your Tears",
  "Harry Styles Late Night Talking",
  "Doja Cat Paint The Town Red"
];

export const chillQueries = [
  "Iktara Wake Up Sid",
  "Shaam Aisha",
  "Khaabon Ke Parinday Zindagi Na Milegi Dobara",
  "Aao Milo Chalo Jab We Met",
  "Tum Se Hi Jab We Met",
  "Aaj Din Chadheya Love Aaj Kal",
  "Kahin To Jaane Tu Ya Jaane Na",
  "Tu Bin Bataye Rang De Basanti",
  "Kya Karoon? Wake Up Sid",
  "Aahista Laila Majnu",
  "Kho Gaye Hum Kahan Baar Baar Dekho",
  "Alag Aasmaan Anuv Jain",
  "Gul Anuv Jain",
  "Baarishein Anuv Jain",
  "Kasoor Prateek Kuhad",
  "cold/mess Prateek Kuhad",
  "Mulaqat Kho Gaye Hum Kahan",
  "Phir Se Ud Chala Rockstar",
  "Safarnama Tamasha",
  "Agar Tum Saath Ho Tamasha",
  "Tu Kya Jaane Amar Singh Chamkila",
  "O Maahi Dunki",
  "Hawayein Jab Harry Met Sejal",
  "Ve Kamleya Rocky Aur Rani Kii Prem Kahaani",
  "Sajni Laapataa Ladies",
  "Apna Bana Le Bhediya",
  "Aise Kyun Mismatched",
  "Chaand Baaliyan Aditya A",
  "Husn Anuv Jain",
  "Jo Tum Mere Ho Anuv Jain",
  "Satranga Animal",
  "Tere Vaaste Zara Hatke Zara Bachke",
  "Aabaad Barbaad Ludo",
  "Ranjha Shershaah",
  "Shayad Love Aaj Kal",
  "Amake Amar Moto Thakte Dao Anupam Roy",
  "Boba Tunnel Anupam Roy",
  "Benche Thakar Gaan Autograph",
  "Amar Mawte Belaseshe",
  "Tumi Jake Bhalobasho Praktan",
  "Bojhena Shey Bojhena",
  "Tomake Chai Gangster",
  "Mon Majhi Re Boss",
  "Pherari Mon Antaheen",
  "Kichu Kotha Chilo Chokhe Antaheen",
  "Majhi Re The Bong Connection",
  "Hariye Giyechi Arnob",
  "Tomar Jonno Arnob",
  "Shey Je Boshe Ache Arnob",
  "Chiltey Roud Fossils",
  "Hashnuhana Fossils",
  "Ekla Ghor Fossils",
  "Aro Ekbar Fossils",
  "Preme Pora Baron Sweater",
  "E Tumi Kemon Tumi Chotushkone",
  "Kolkata Anupam Roy",
  "Tumi Ashbe Bole Chotushkone",
  "Jani Dekha Hobe Bojhena Shey Bojhena",
  "Bhalobashar Morshum X=Prem",
  "Oboseshe Kishmish",
  "Abar Phire Ele Dwitiyo Purush",
  "Mon Kyamoner Jonmodin Hridpindo",
  "Tapa Tini Belashuru",
  "Monta Ahare Belashuru",
  "Tomar Holo Shuru Rabindra Sangeet",
  "Amaro Porano Jaha Chay Rabindra Sangeet",
  "Majhe Majhe Tobo Dekha Pai Rabindra Sangeet",
  "Tumi Robe Nirobe Rabindra Sangeet",
  "Ami Tomaro Shonge Bedhechi Amar Pran Rabindra Sangeet",
  "Pagla Hawar Badol Dine Rabindra Sangeet"
];

export const sadQueries = [
  "Agar Tum Saath Ho Tamasha",
  "Channa Mereya Ae Dil Hai Mushkil",
  "Aaj Jaane Ki Zid Na Karo Farida Khanum",
  "Phir Le Aaya Dil Barfi!",
  "Hamari Adhuri Kahani Hamari Adhuri Kahani",
  "Tum Hi Ho Aashiqui 2",
  "Tujhe Kitna Chahne Lage Kabir Singh",
  "Humdard Ek Villain",
  "Main Rahoon Ya Na Rahoon Armaan Malik",
  "Mann Bharryaa 2.0 Shershaah",
  "Tera Yaar Hoon Main Sonu Ke Titu Ki Sweety",
  "Tune Jo Na Kaha New York",
  "Sach Keh Raha Hai Deewana Rehnaa Hai Terre Dil Mein",
  "Tadap Tadap Hum Dil De Chuke Sanam",
  "Judaai I Love NY",
  "Bhula Dena Aashiqui 2",
  "Milne Mujhse Aayi Aashiqui 2",
  "Lo Maan Liya Raaz Reboot",
  "Humnava Hamari Adhuri Kahani",
  "Zaroorat Ek Villain",
  "Aye Khuda Paathshaala",
  "Tujhe Bhula Diya Anjaana Anjaani",
  "Ya Rabba Salaam-e-Ishq",
  "Tanhayee Dil Chahta Hai",
  "Koi Fariyaad Tum Bin",
  "Woh Lamhe Woh Baatein Zeher",
  "Tu Jaane Na Ajab Prem Ki Ghazab Kahani",
  "Tera Hone Laga Hoon Ajab Prem Ki Ghazab Kahani",
  "Kaise Hua Kabir Singh",
  "Bekhayali Kabir Singh",
  "Phir Bhi Tumko Chaahunga Half Girlfriend",
  "Ae Dil Hai Mushkil Ae Dil Hai Mushkil",
  "Ishq Wala Love Student of the Year",
  "Tujh Mein Rab Dikhta Hai Rab Ne Bana Di Jodi",
  "Tum Se Hi Jab We Met",
  "Shey Je Boshe Ache Arnob",
  "Chol Paltai Chalo Paltai",
  "Ami Shudhu Je Tomar Bojhena Shey Bojhena",
  "Jani Dekha Hobe Bojhena Shey Bojhena",
  "Tumi Jake Bhalobasho Praktan",
  "Kichu Kotha Chilo Chokhe Antaheen",
  "Pherari Mon Antaheen",
  "E Tumi Kemon Tumi Chotushkone",
  "Benche Thakar Gaan Autograph",
  "Amake Amar Moto Thakte Dao Autograph",
  "Boba Tunnel Anupam Roy",
  "Ekbar Bol Autograph",
  "Tomake Chai Gangster",
  "Mon Majhi Re Boss",
  "Tumi Ashbe Bole Chotushkone",
  "Bhalobashar Morshum X=Prem",
  "Oboseshe Kishmish",
  "Abar Phire Ele Dwitiyo Purush",
  "Preme Pora Baron Sweater",
  "Adure Din Sweater",
  "Kolkata Anupam Roy",
  "Amar Bhindeshi Tara Chandrabindoo",
  "Bhalo Theko Moner Manush",
  "Moner Manush Moner Manush",
  "Hariye Giyechi Arnob",
  "Tomar Jonno Arnob",
  "Chiltey Roud Fossils",
  "Aro Ekbar Fossils",
  "Hashnuhana Fossils",
  "Ekla Ghor Fossils",
  "Amar Mawte Belaseshe",
  "Monta Ahare Belashuru",
  "Tumi Robe Nirobe Rabindra Sangeet",
  "Amaro Porano Jaha Chay Rabindra Sangeet",
  "Majhe Majhe Tobo Dekha Pai Rabindra Sangeet"
];

export const partyQueries = [
  "It's Magic Koi... Mil Gaya",
  "You Are My Soniya Kabhi Khushi Kabhie Gham",
  "It's the Time to Disco Kal Ho Naa Ho",
  "Dus Bahane Dus",
  "Where's the Party Tonight Kabhi Alvida Naa Kehna",
  "Dard-e-Disco Om Shanti Om",
  "Deewangi Deewangi Om Shanti Om",
  "Mauja Hi Mauja Jab We Met",
  "Nagada Nagada Jab We Met",
  "Aahun Aahun Love Aaj Kal",
  "Twist Love Aaj Kal",
  "Pungi Agent Vinod",
  "Fevicol Se Dabangg 2",
  "Party On My Mind Race 2",
  "Badtameez Dil Yeh Jawaani Hai Deewani",
  "Balam Pichkari Yeh Jawaani Hai Deewani",
  "Ghagra Yeh Jawaani Hai Deewani",
  "Abhi Toh Party Shuru Hui Hai Khoobsurat",
  "Saturday Saturday Humpty Sharma Ki Dulhania",
  "Kar Gayi Chull Kapoor & Sons",
  "Kala Chashma Baar Baar Dekho",
  "The Breakup Song Ae Dil Hai Mushkil",
  "Cutiepie Ae Dil Hai Mushkil",
  "Galti Se Mistake Jagga Jasoos",
  "Swag Se Swagat Tiger Zinda Hai",
  "Dil Chori Sonu Ke Titu Ki Sweety",
  "High Rated Gabru Nawabzaade",
  "Morni Banke Badhaai Ho",
  "Aankh Marey Simmba",
  "Mungda Total Dhamaal",
  "Muqabla Street Dancer 3D",
  "Garmi Street Dancer 3D",
  "What Jhumka? Rocky Aur Rani Kii Prem Kahaani",
  "Jhoome Jo Pathaan Pathaan",
  "Not Ramaiya Vastavaiya Jawan",
  "What Makes You Beautiful One Direction",
  "Ghungroo War",
  "Nashe Si Chadh Gayi Befikre",
  "Bom Diggy Diggy Sonu Ke Titu Ki Sweety",
  "Proper Patola Namaste England",
  "Bojhena Shey Bojhena",
  "Kolkata Rap Bhooter Bhabishyat",
  "Paglu Thakish Na Paglu",
  "Khokababu Khokababu",
  "Prem Leela Paglu 2",
  "Besh Korechi Prem Korechi",
  "Crazy Ki Korbo Ki Kore Toke Bolbo",
  "Dhat Teri Ki Herogiri",
  "Bojhena Shey Bojhena Dance Mix",
  "Tui Chunli Jakhan Herogiri",
  "Kolkata Chalantika",
  "Chalti Ka Naam Gaadi Zulfiqar",
  "Dhaker Taale Komor Dole Parbona Ami Charte Toke",
  "Bhalobashbo Basbo Re Love Express",
  "Party Shuru Har Har Byomkesh",
  "Ranjana Ami Ar Ashbona Anjan Dutt",
  "Bhalo Achi Bhalo Theko Moner Manush",
  "Shundori Komola",
  "Komola Nritto Kore",
  "Dhono Dhanno Pushpe Bhora",
  "Amra Sobai Raja",
  "Laal Paharir Deshe Ja",
  "Hariye Jao Bishorjon",
  "Tapa Tini Belashuru",
  "Monta Ahare Belashuru",
  "Bhalobashar Morshum X=Prem",
  "Sajani Go Raktabeej",
  "Dugga Elo",
  "Bolo Dugga Mai Ki",
  "Bhalobasha Aajkal Bhalobasha Aajkal"
];

export const focusQueries = [
  "Ishq Bina Taal",
  "Nahin Saamne Tu Taal",
  "O Re Piya Aaja Nachle",
  "Mora Piya Raajneeti",
  "Tu Hi Re Bombay",
  "Roja Jaaneman Roja",
  "Tu Hi Tu Kabir Singh",
  "Aayat Bajirao Mastani",
  "Laal Ishq Goliyon Ki Raasleela Ram-Leela",
  "Arziyan Delhi-6",
  "Kun Faya Kun Rockstar",
  "Nadaan Parindey Rockstar",
  "Jo Bhi Main Rockstar",
  "Sadda Haq Rockstar",
  "Aazaadiyan Udaan",
  "Manja Kai Po Che!",
  "Shaam Aisha",
  "Aahista Aahista Bachna Ae Haseeno",
  "Ishq Hai Ishq Hai",
  "Aise Kyun Mismatched",
  "Kho Gaye Hum Kahan Baar Baar Dekho",
  "Phir Se Ud Chala Rockstar",
  "Safarnama Tamasha",
  "Tu Kisi Rail Si Masaan",
  "Chaandaniya 2 States",
  "Shikayatein Lootera",
  "Manmarziyan Lootera",
  "Montu Laila Majnu",
  "Aahista Laila Majnu",
  "Mehrama Love Aaj Kal",
  "Qaafirana Kedarnath",
  "Monta Re Lootera",
  "Ishq Di Galiyan Jabariya Jodi",
  "Ranjha Shershaah",
  "Ishq Wala Love Student of the Year",
  "Shey Je Boshe Ache Arnob",
  "Tomar Jonno Arnob",
  "Hariye Giyechi Arnob",
  "Chiltey Roud Fossils",
  "Aro Ekbar Fossils",
  "Ekla Ghor Fossils",
  "Hashnuhana Fossils",
  "Amake Amar Moto Thakte Dao Anupam Roy",
  "Boba Tunnel Anupam Roy",
  "Kolkata Anupam Roy",
  "E Tumi Kemon Tumi Anupam Roy",
  "Tumi Jake Bhalobasho Praktan",
  "Kichu Kotha Chilo Chokhe Antaheen",
  "Pherari Mon Antaheen",
  "Majhi Re The Bong Connection",
  "Mon Majhi Re Boss",
  "Tomake Chai Gangster",
  "Jani Dekha Hobe Bojhena Shey Bojhena",
  "Bhalobashar Morshum X=Prem",
  "Oboseshe Kishmish",
  "Amaro Porano Jaha Chay",
  "Tumi Robe Nirobe",
  "Majhe Majhe Tobo Dekha Pai",
  "Ami Tomaro Shonge Bedhechi Amar Pran",
  "Tomar Holo Shuru",
  "Pagla Hawar Badol Dine",
  "Amar Hiyar Majhe",
  "Mone Ki Dwidha Rekhe Gele Chole",
  "Jodi Tare Nai Chini Go",
  "Ami Chini Go Chini",
  "Sokhi Bhabona Kahare Bole",
  "Tumi Sondhyaro Meghomala",
  "Aji Jhorer Rate Tomar Abhisar",
  "Madhur Tomar Shesh Je Na Pai",
  "Keno Megh Ashe Hridoy Akashe"
];
